pipeline {
  agent any 
    stages {
      stage('Checkout') {
        steps {
          sh 'git branch: 'main', url: 'https://github.com/nikitapatil1203/CI-CD''
        }
      }
      stage('Build and Test') {
        steps {
          sh 'cd spring-boot-app && mvn clean package'
        }
      }
      stage('Static Code Analysis') {
        steps {
          withSonarQubeEnv(credentialsId: 'sonarqube') {
             sh 'mvn sonar:sonar && -Dsonar.url=http://44.210.99.200:9000/ && -Dsonar.login=sqa_4fccb5944aa0455e3cd83152185e07e5c199972c'
           }
        }
      }






        
      }
    }
  


  

